<?php

// tests/EndToEnd/TailwindIngestionTest.php
declare(strict_types=1);

use Pliego\Css\StylesheetParser;
use Pliego\Css\Value\Color;

/**
 * M10-T3: the closing E2E for "does pliego actually swallow a REAL Tailwind v4 CLI build output" --
 * same structure as BootstrapIngestionTest.php (M9-T2), two separate concerns:
 *
 *  1. Ingestion: parse the ENTIRE vendored fixture (tests/Fixtures/tailwind/tailwind-output.css,
 *     MIT, generated by the real `@tailwindcss/cli` v4.3.2 -- see LICENSE-tailwind.txt alongside it
 *     and this file's own docblock for the exact generation command) end to end through
 *     StylesheetParser -- no exception, bounded time.
 *  2. Warning audit: every warning the real build output produces gets bucketed by a
 *     regex-per-category classifier (tailwindIngestionCategorizeWarning() below) and the resulting
 *     category => count table is pinned as a golden snapshot, WITH a total -- same "honest
 *     capability audit" contract as Bootstrap's (a non-empty 'other' bucket means some warning
 *     SHAPE isn't accounted for yet, asserted empty so the table stays a COMPLETE partition).
 *
 * Provenance (brief M10-T3: "generar UNA VEZ con el CLI standalone... vendorizar el output como
 * fixture pinneada"): tests/Fixtures/tailwind/utilities.html is a representative page (spacing
 * utilities like p-4 and m-2 and gap-4, flex row/col/wrap/justify/items, grid classes INCLUDED
 * deliberately -- see the 'unsupported-property-other' category below for
 * grid-template-columns/grid-column/grid-row and 'unsupported-keyword' for `display: grid` --
 * this engine has no grid layout, part of the audit's job is to PROVE that gap honestly rather
 * than hide it by omission -- colors like bg-blue-500/text-slate-700 across several scales
 * (blue/slate/red/green/amber/emerald/indigo), typography, borders/rounded, shadows,
 * width/height, and a table using odd/even variants) was fed to the real
 * `@tailwindcss/cli` v4.3.2 (installed locally via `npm install tailwindcss@latest
 * @tailwindcss/cli@latest`, found reachable via `npx` per the check-local-first rule -- no
 * standalone binary was already vendored anywhere else on disk, see the M10-T3 report for the
 * full search):
 *
 *   npx tailwindcss -i input.css -o tailwind-output.css --content utilities.html --minify=false
 *
 * where input.css is the one-line `@import "tailwindcss";` entry point Tailwind v4 uses instead of
 * v3's `@tailwind base/components/utilities;` directives. The output is vendored VERBATIM
 * (byte-for-byte, unminified so the @layer structure stays human-legible for the report), MIT
 * license preserved alongside it -- exact version pinned above and in the report.
 */

const TAILWIND_INGESTION_CSS_PATH = __DIR__ . '/../Fixtures/tailwind/tailwind-output.css';

function tailwindIngestionCss(): string
{
    $css = file_get_contents(TAILWIND_INGESTION_CSS_PATH);
    if ($css === false) {
        throw new RuntimeException('Missing vendored fixture: ' . TAILWIND_INGESTION_CSS_PATH);
    }
    return $css;
}

/**
 * Regex-per-category classifier for the warning audit (see class docblock). Order matters -- most
 * specific first, same convention as BootstrapIngestionTest's own classifier. The three M10-T3
 * aggregated at-rule/layer categories (media-skipped/property-skipped/layer-important-simplified)
 * and the color-mix() fallback are checked FIRST since their message shapes are otherwise generic
 * enough to risk drifting into a later bucket. `default => 'other'` is the safety net asserted to
 * never fire for the real fixture.
 */
function tailwindIngestionCategorizeWarning(string $warning): string
{
    return match (true) {
        (bool) preg_match('/@media rule blocks skipped/', $warning) => 'media-skipped',
        (bool) preg_match('/@property rule blocks skipped/', $warning) => 'property-skipped',
        (bool) preg_match('/^layered !important uses simplified precedence/', $warning) => 'layer-important-simplified',
        (bool) preg_match('/^color-mix\(\) is not supported/', $warning) => 'color-mix-fallback',
        (bool) preg_match('/^Invalid selector syntax:/', $warning) => 'invalid-selector',
        (bool) preg_match('/^Unknown pseudo-class:/', $warning) => 'pseudo-unknown',
        (bool) preg_match('/^Unsupported color for/', $warning) => 'unsupported-color',
        (bool) preg_match('/^Unsupported length for/', $warning) => 'unsupported-length',
        (bool) preg_match('/^Unsupported font-weight:/', $warning) => 'unsupported-font-weight',
        (bool) preg_match('/^Unsupported vertical-align:/', $warning) => 'unsupported-vertical-align',
        (bool) preg_match('/^Unsupported text-align:/', $warning) => 'unsupported-text-align',
        (bool) preg_match('/^Unsupported text-decoration:/', $warning) => 'unsupported-text-decoration',
        (bool) preg_match('/^Unsupported keyword for/', $warning) => 'unsupported-keyword',
        (bool) preg_match('/^Unsupported shorthand for/', $warning) => 'unsupported-shorthand',
        (bool) preg_match('/^Invalid calc\(\) expression:/', $warning) => 'invalid-calc',
        (bool) preg_match('/^Unsupported property:/', $warning) => 'unsupported-property-other',
        default => 'other',
    };
}

/**
 * @param list<string> $warnings
 * @return array<string, int>
 */
function tailwindIngestionAuditWarnings(array $warnings): array
{
    $counts = [];
    foreach ($warnings as $warning) {
        $category = tailwindIngestionCategorizeWarning($warning);
        $counts[$category] = ($counts[$category] ?? 0) + 1;
    }
    ksort($counts);
    return $counts;
}

function assertMatchesTailwindIngestionGolden(string $name, mixed $dump): void
{
    $path = __DIR__ . '/goldens/' . $name . '.json';
    $encoded = json_encode($dump, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRESERVE_ZERO_FRACTION);
    if ($encoded === false) {
        throw new RuntimeException("Failed to encode golden dump '$name' as JSON");
    }
    $json = $encoded . "\n";

    if (getenv('UPDATE_GOLDENS') === '1') {
        file_put_contents($path, $json);
        test()->markTestSkipped('golden regenerated');
    }

    $raw = file_get_contents($path);
    if ($raw === false) {
        throw new RuntimeException("Missing golden file: $path (run with UPDATE_GOLDENS=1 to generate it)");
    }
    $golden = json_decode($raw, true, flags: JSON_THROW_ON_ERROR);
    expect($dump)->toBe($golden);
}

// --- Ingestion: the whole real Tailwind v4 build, no exception, bounded time -------------------

it('parses the ENTIRE real vendored Tailwind v4 CLI output with no exception and in bounded time', function () {
    $css = tailwindIngestionCss();
    // Sanity on the fixture itself -- if this ever shrinks/changes shape the vendored file was
    // probably swapped for something else by accident.
    expect(strlen($css))->toBeGreaterThan(15_000);
    expect($css)->toStartWith('/*! tailwindcss v4');
    expect($css)->toContain('@layer theme, base, components, utilities;');
    expect($css)->toContain('oklch(');

    $start = microtime(true);
    $result = new StylesheetParser()->parse($css);
    $elapsedMs = (microtime(true) - $start) * 1000;

    // Bounded, not tight -- a "did something go quadratic" tripwire, not a perf budget (that lives
    // in TailwindPerfTest.php, against a full Engine::render(), a stricter number).
    expect($elapsedMs)->toBeLessThan(3000.0);

    expect($result->rules)->not->toBeEmpty();
    expect(count($result->rules))->toBeGreaterThan(150);
});

// --- Warning audit: full categorized breakdown, pinned as a golden snapshot with a total --------

it('audits every warning the real Tailwind v4 build produces into a categorized, total-pinned breakdown (honest capability audit)', function () {
    $result = new StylesheetParser()->parse(tailwindIngestionCss());

    $byCategory = tailwindIngestionAuditWarnings($result->warnings);

    // The classifier's `default => 'other'` arm must never fire -- if it does, some new warning
    // SHAPE showed up that isn't accounted for by any category yet.
    expect($byCategory)->not->toHaveKey('other');

    $sumOfCategories = array_sum($byCategory);
    expect($sumOfCategories)->toBe(count($result->warnings));

    assertMatchesTailwindIngestionGolden('tailwind-warning-audit', [
        'total' => count($result->warnings),
        'byCategory' => $byCategory,
    ]);
});

it('aggregates every skipped @property rule into exactly ONE warning with the real total count', function () {
    $result = new StylesheetParser()->parse(tailwindIngestionCss());
    $propertyWarnings = array_values(array_filter(
        $result->warnings,
        static fn(string $w): bool => str_contains($w, '@property rule blocks skipped'),
    ));
    expect($propertyWarnings)->toHaveCount(1);
    expect($propertyWarnings[0])->toMatch('/^\d+ @property rule blocks skipped \(not supported\)$/');
});

it('warns exactly once about layered !important (the real fixture\'s preflight has one, inside @layer base)', function () {
    $result = new StylesheetParser()->parse(tailwindIngestionCss());
    $layerWarnings = array_values(array_filter(
        $result->warnings,
        static fn(string $w): bool => str_contains($w, 'layered !important uses simplified precedence'),
    ));
    expect($layerWarnings)->toHaveCount(1);
});

it('resolves the real Tailwind blue-500/red-600/slate-900 theme colors via oklch(), reachable through their utility classes\' var() chain', function () {
    $result = new StylesheetParser()->parse(tailwindIngestionCss());
    // The utility rules reference var(--color-*); the underlying oklch() literal only lives in the
    // :root theme custom-property declarations, unresolved (DeferredDeclaration) until compute-time
    // -- see StyleResolverTest/Style tests for the full var()-resolution path. Here we only assert
    // the RAW custom property text made it through parsing untouched (css-variables-1 custom
    // properties are captured raw, never typed at parse time, see StylesheetParser::mergeDeclaration()),
    // searching declarations across ALL rules for the theme custom properties (no dependency on
    // ComplexSelector's internal shape -- this assertion only needs the DECLARATIONS).
    // NOTE: the real CLI output writes chroma with a LEADING-DOT decimal (".214", not "0.214") --
    // Color::fromCss()'s oklch() regex accepts this natively (see ColorTest.php), asserted here
    // via the actual raw vendored text rather than the "0.214" shape one might assume by hand.
    $hasBlue500 = false;
    $hasRed600 = false;
    foreach ($result->rules as $rule) {
        if (($rule->declarations['--color-blue-500'] ?? null) === 'oklch(62.3% .214 259.815)') {
            $hasBlue500 = true;
        }
        if (($rule->declarations['--color-red-600'] ?? null) === 'oklch(57.7% .245 27.325)') {
            $hasRed600 = true;
        }
    }
    expect($hasBlue500)->toBeTrue();
    expect($hasRed600)->toBeTrue();
    expect(Color::fromCss('oklch(62.3% .214 259.815)'))->toEqual(new Color(0x2b, 0x7f, 0xff));
});
